services:
  service1:
    build:
      context: ./service1
      dockerfile: Dockerfile
    image: service1:latest
    ports: 
      - "8199:8199"
    volumes:
      - vStorage:/data
    networks:
      - internal
      - public
    user: root # I understand that this is not the smartest solution, but this was the only way I could give Node access to vStorage
  service2:
    build:
      context: ./service2
      dockerfile: Dockerfile
    image: service2:latest
    expose:
      - "5000"
    volumes:
      - vStorage:/data
    networks:
      - internal
  storage:
    build:
      context: ./storage
      dockerfile: Dockerfile
    image: storage:latest
    expose:
      - "6000"
    volumes:
      - Storage:/data
    networks:
      - internal

volumes:
  vStorage:
    driver: local
  Storage:
    driver: local

networks:
  public:
    driver: bridge
  internal:
    driver: bridge
